name: Init
initial_state: THRUSTER_PRE_INIT_INDICATION
states:
  THRUSTER_PRE_INIT_INDICATION:
    action: 
      type: Surge
      value: 100
      duration: 0.5
  RESET_IMU:
    action: 
      type: ResetIMU
      duration: 1
  ENABLE_STABILIZATION:
    action: 
      type: Stabilization
      surge: false
      sway: false
      depth: true
      roll: false
      pitch: false
      yaw: true
  THRUSTER_AFTER_IMU_INDICATION:
    action: 
      type: Surge
      value: 100
      duration: 0.1
transitions:
  - { trigger: ok, source: THRUSTER_PRE_INIT_INDICATION, dest: RESET_IMU }
  - { trigger: ok, source: RESET_IMU, dest: ENABLE_STABILIZATION }
  - { trigger: ok, source: ENABLE_STABILIZATION, dest: THRUSTER_AFTER_IMU_INDICATION }
  - { trigger: ok, source: THRUSTER_AFTER_IMU_INDICATION, dest: SUCCESS }
  - { trigger: fail, source: "*", dest: FAILURE }
  - { trigger: timeout, source: "*", dest: FAILURE }
