mission_name: search
states: 
  - rotate_clockwise
  - rotate_counter_clockwise
transitions: 
  - {trigger: go, source: start, dest: rotate_counter_clockwise}
  - {trigger: found, source: [rotate_clockwise, rotate_counter_clockwise], dest: finish}
  - {trigger: not_found, source: rotate_clockwise, dest: rotate_counter_clockwise}
  - {trigger: not_found, source: rotate_counter_clockwise, dest: finish}
events: 
  - {type: TopicEvent, topic: /stingray/mission/search/rotate_clockwise, trigger: found, count: 5, data: gate}